{% set name = "lsstdesc-gcr-catalogs" %}
{% set version = "1.10.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/LSSTDESC/gcr-catalogs/archive/v{{ version }}.tar.gz
  sha256: 3cdc91bf95c4d24306f9a0649cc6ed72625bd4543f60a2969f220a5a3250be85

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - python >={{ python_min }}
    - requests
    - pyyaml
    - numpy
    - astropy-base
    - gcr >=0.9.2
    - h5py
    - healpy
    - pandas
    - pyarrow
    - pytables
    - python-blosc2  # needed by pytables

test:
  source_files:
    - conftest.py
    - tests/
  imports:
    - GCRCatalogs
  commands:
    - pip check
    - pytest --no-catalog
  requires:
    - pip
    - pytest
    - python {{ python_min }}

about:
  home: https://github.com/LSSTDESC/gcr-catalogs
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: A repository of data catalogs for the LSST Dark Energy Science Collaboration (DESC)
  description: |
    GCRCatalogs is a Python package that serves as a catalog repository for 
    the Rubin LSST Dark Energy Science Collaboration (DESC). 
    It provides a unified user interface to access all catalogs by using 
    the Generic Catalog Reader (GCR) base class.
  doc_url: https://github.com/LSSTDESC/gcr-catalogs/blob/master/README.md
  dev_url: https://github.com/LSSTDESC/gcr-catalogs

extra:
  recipe-maintainers:
    - yymao
    - JoanneBogart
    - heather999
